// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007204812_Re-FixedPaymentCreatedAt")]
    partial class ReFixedPaymentCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.CategoryModel", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("ImageCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            ImageCategory = "Drum.png",
                            NameCategory = "Drum"
                        },
                        new
                        {
                            IdCategory = 2,
                            ImageCategory = "Piano.png",
                            NameCategory = "Piano"
                        },
                        new
                        {
                            IdCategory = 3,
                            ImageCategory = "Gitar.png",
                            NameCategory = "Gitar"
                        },
                        new
                        {
                            IdCategory = 4,
                            ImageCategory = "Biola.png",
                            NameCategory = "Biola"
                        },
                        new
                        {
                            IdCategory = 5,
                            ImageCategory = "Saxophone.png",
                            NameCategory = "Saxophone"
                        },
                        new
                        {
                            IdCategory = 6,
                            ImageCategory = "Saxophone.png",
                            NameCategory = "Flute"
                        },
                        new
                        {
                            IdCategory = 7,
                            ImageCategory = "Gitar.png",
                            NameCategory = "Bass"
                        },
                        new
                        {
                            IdCategory = 8,
                            ImageCategory = "Menyanyi.png",
                            NameCategory = "Menyanyi"
                        });
                });

            modelBuilder.Entity("Backend.Models.CheckoutModel", b =>
                {
                    b.Property<int>("IdCheckout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCheckout"));

                    b.Property<int>("IdCourse")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("Jadwal")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCheckout");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdUser");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("Backend.Models.DataCourseModel", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCourse"));

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("ImageCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaCourse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCourse");

                    b.HasIndex("IdCategory");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            IdCourse = 1,
                            Harga = 8500000m,
                            IdCategory = 1,
                            ImageCourse = "d4.png",
                            NamaCourse = "Kursus Drummer Special Coach (Eno Netral)"
                        },
                        new
                        {
                            IdCourse = 2,
                            Harga = 5450000m,
                            IdCategory = 1,
                            ImageCourse = "d1.png",
                            NamaCourse = "Expert Level Drummer Lessons"
                        },
                        new
                        {
                            IdCourse = 3,
                            Harga = 13000000m,
                            IdCategory = 1,
                            ImageCourse = "d2.png",
                            NamaCourse = "From Zero to Professional Drummer (Complit Package)"
                        },
                        new
                        {
                            IdCourse = 4,
                            Harga = 2200000m,
                            IdCategory = 1,
                            ImageCourse = "d3.png",
                            NamaCourse = "Drummer for kids (Level Basic/1)"
                        },
                        new
                        {
                            IdCourse = 5,
                            Harga = 11650000m,
                            IdCategory = 2,
                            ImageCourse = "Copy of Rectangle 12-5.png",
                            NamaCourse = "Kursu Piano : From Zero to Pro (Full Package)"
                        },
                        new
                        {
                            IdCourse = 6,
                            Harga = 1600000m,
                            IdCategory = 3,
                            ImageCourse = "Copy of Rectangle 12-2.png",
                            NamaCourse = "[Beginner] Guitar class for kids "
                        },
                        new
                        {
                            IdCourse = 7,
                            Harga = 3000000m,
                            IdCategory = 4,
                            ImageCourse = "Copy of Rectangle 12-3.png",
                            NamaCourse = "Biola Mid-Level Course"
                        },
                        new
                        {
                            IdCourse = 8,
                            Harga = 7350000m,
                            IdCategory = 5,
                            ImageCourse = "Copy of Rectangle 12-6.png",
                            NamaCourse = "Expert Level Saxophone"
                        });
                });

            modelBuilder.Entity("Backend.Models.PaymentMethodModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo_Methode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Methode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Backend.Models.PaymentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodModelId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdPaymentMethod");

                    b.HasIndex("IdUser");

                    b.HasIndex("PaymentMethodModelId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Backend.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.CheckoutModel", b =>
                {
                    b.HasOne("Backend.Models.DataCourseModel", "Course")
                        .WithMany()
                        .HasForeignKey("IdCourse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.UserModel", "User")
                        .WithMany("Checkouts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.DataCourseModel", b =>
                {
                    b.HasOne("Backend.Models.CategoryModel", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.PaymentModel", b =>
                {
                    b.HasOne("Backend.Models.PaymentMethodModel", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("IdPaymentMethod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.UserModel", "User")
                        .WithMany("Payments")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.PaymentMethodModel", null)
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodModelId");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.CategoryModel", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Backend.Models.PaymentMethodModel", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Backend.Models.UserModel", b =>
                {
                    b.Navigation("Checkouts");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
